/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 21 18:32:40 GMT 2021
 */

package org.apache.commons.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.nio.ByteOrder;
import org.apache.commons.io.ByteOrderParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ByteOrderParser_ESTest extends ByteOrderParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        ByteOrderParser.parseByteOrder("q");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported byte order setting: q, expeced one of LITTLE_ENDIAN, BIG_ENDIAN
         //
         verifyException("org.apache.commons.io.ByteOrderParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ByteOrder byteOrder0 = ByteOrderParser.parseByteOrder("BIG_ENDIAN");
      assertEquals("BIG_ENDIAN", byteOrder0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ByteOrder byteOrder0 = ByteOrderParser.parseByteOrder("LITTLE_ENDIAN");
      assertEquals("LITTLE_ENDIAN", byteOrder0.toString());
  }
}
